const testData = [
    {
        number: "001",
        lv1: "Lv1-a",
        lv2: "Lv2-a",
        lv3: "Lv3-a",
        question: "あたらしい新しいプロジェクトを始める際に注意すべき点は何ですか？",
        answer: "目的の明確化と関係者との初期調整が重要です。",
        source: "",
    },
    {
        number: "002",
        lv1: "Lv1-b",
        lv2: "Lv2-b",
        lv3: "Lv3-b",
        question: "チームの生産性を高めるにはどうすればいいですか？",
        answer: "(1行目)定期的なコミュニケーションを取りましょう。\n(2行目)タスクの優先順位も明確にすることが大切です。",
        source: "",
    },
    {
        number: "003",
        lv1: "Lv1-c",
        lv2: "Lv2-c",
        lv3: "Lv3-c",
        question: "リモートワークに適したツールには何がありますか？",
        answer: "Slack、Zoom、Notionなどが代表的なツールです。",
        source: "",
    },
    {
        number: "004",
        lv1: "Lv1-d",
        lv2: "Lv2-d",
        lv3: "Lv3-d",
        question: "目標設定を効果的に行うにはどうしたらいいですか？",
        answer: "(1行目)SMARTの原則に従って設定します。\n(2行目)達成可能かつ具体的であることが重要です。",
        source: "",
    },
    {
        number: "005",
        lv1: "Lv1-e",
        lv2: "Lv2-e",
        lv3: "Lv3-e",
        question: "業務改善のアイデアを集めるには？",
        answer: "定期的なアンケートや現場ヒアリングが効果的です。",
        source: "",
    },
];
